services:
  # Web App Services
  db-web:
    image: postgres:17
    profiles: [web]
    ports:
      - "${WEB_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web
    volumes:
      - web_postgres_data:/var/lib/postgresql/data

  redis-web:
    image: redis:latest
    profiles: [web]
    ports:
      - "${WEB_REDIS_PORT:-6379}:6379"
    volumes:
      - web_redis_data:/data

volumes:
  web_postgres_data:
  web_redis_data:
